name: Test Coverage

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        architecture:
          [
            "x86-linux-gnu",
            "x86-linux-musl",
            "x86_64-linux-gnu",
            "x86_64-linux-musl",
          ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0

      - name: Install kcov
        working-directory: ./Tez
        run: |
          wget https://github.com/SimonKagstrom/kcov/releases/download/v42/kcov-amd64.tar.gz
          tar xzf kcov-amd64.tar.gz
          install -Dm755 usr/local/bin/kcov /usr/local/bin/kcov

      - name: Test
        working-directory: ./Tez
        run: |
          zig build -Dtarget=${{ matrix.architecture }} test -Dtest-coverage --summary all
          COVERAGE_PERCENTAGE=$(jq -r '.percent_covered' kcov-output/test/coverage.json)
          echo "COVERAGE_PERCENTAGE=$COVERAGE_PERCENTAGE" >> $GITHUB_ENV

      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        working-directory: ./Tez
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 1aca0cde5f6b0339e41cf8d7b6a09d5e
          filename: test.json
          label: Test Coverage
          message: ${{ env.COVERAGE_PERCENTAGE }}%
          valColorRange: ${{ env.COVERAGE_PERCENTAGE }}
          maxColorRange: 100
          minColorRange: 0
